networks:
  internal-net:
    driver: bridge

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - internal-net

  backend:
    build: ./backend
    networks:
      - internal-net